name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      environment:
        type: environment
        required: true

jobs:
  
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ghcr.io/${{ github.repository_owner }}/hello-world:latest
        push: true
