name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ghcr.io/${{ github.repository_owner }}/hello-world:latest
        push: true
        
    - name: Notify via ntfy
      run: curl -d "Build ghcr.io/${{ github.repository_owner }}/hello-world:latest successfully" ntfy.sh/gh-action-ici

    - uses: serversideup/github-action-docker-swarm-deploy@v3
      env:
        IMAGE: ghcr.io/${{ github.repository_owner }}/hello-world:latest
      with:
        ssh_deploy_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
        ssh_remote_hostname: "${{ secrets.SSH_HOST }}"
        registry: "ghcr.io"
        registry-username: "${{ github.actor }}"
        registry-password: "${{ secrets.GITHUB_TOKEN }}"
        stack_name: "hello-world"
        
    - name: Notify via ntfy
      run: curl -d "Deployed ghcr.io/${{ github.repository_owner }}/hello-world:latest successfully (${{ inputs.environment }})" ntfy.sh/gh-action-ici
